name: RUN UNIT TESTS

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ${{ matrix.os}}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        
        steps:
         - name : checkout code
           uses: actions/checkout@v3 

         - name: get Python 
           uses: actions/setup-python@v4
           with:
            python-version: '3.x'
         
         - name: run tests
           run: |
                python -m unittest discover -s . -p "*_test.py"

            
